name: NiveriaAPI Build & Test

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - ".coderabbit.yaml"
    branches: [ '**' ]
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - ".coderabbit.yaml"
    branches: [ 'master' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
  JAVA_VERSION: "21"
  GRAALVM_DISTRIBUTION: "graalvm"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name:  Cache GraalVM
        id: cache-graalvm
        uses: actions/cache@v4
        with:
          path:  ${{ runner.tool_cache }}/Java_${{ env.GRAALVM_DISTRIBUTION }}_jdk-${{ env.JAVA_VERSION }}*
          key: ${{ runner.os }}-graalvm-${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/gradle/*
          key:  ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up GraalVM JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Tests with Gradle
        run: ./gradlew test --stacktrace --build-cache

      - name: Report test results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true


  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache GraalVM
        id: cache-graalvm
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/Java_${{ env.GRAALVM_DISTRIBUTION }}_jdk-${{ env.JAVA_VERSION }}*
          key: ${{ runner.os }}-graalvm-${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/gradle/*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up GraalVM JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Derive short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build with snapshot version
        env:
          SNAPSHOT: true
          GITHUB_SHA: ${{ github.sha }}
        run: ./gradlew jar javadocJar sourcesJar -x test --stacktrace --build-cache

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v5
        with:
          name: NiveriaAPI-${{ env.SHORT_SHA }}
          path: build/libs/*